---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  labels:
    app: prowlarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      #hostNetwork: true
      containers:
      - name: prowlarr
        imagePullPolicy: "Always"
        image: lscr.io/linuxserver/prowlarr:develop 
        ports:
        - name: http
          containerPort: 9696
          protocol: TCP
        env:
        - name: TZ
          value: "America/Denver"
        - name: PUID
          value: "666"
        - name: GUID
          value: "321"
        volumeMounts:
        - name: k8s-pv02
          mountPath: /config
          subPath: prowlarr/config
      volumes:
      - name: k8s-pv02
        persistentVolumeClaim:
          claimName: synology-k8s-pv02
